#!/bin/bash

# 批量更新剩余工具的辅助脚本
# 这个脚本列出所有需要更新的工具

echo "=== 剩余待更新工具列表 ==="
echo ""
echo "✅ 已完成 (5/31):"
echo "1. CaseConverter.tsx"
echo "2. WordCounter.tsx"
echo "3. TextSorter.tsx"
echo "4. TextDiff.tsx"
echo "5. PasswordGenerator.tsx"
echo ""
echo "🔄 待处理 (26/31):"
echo ""
echo "转换工具:"
echo "- Base64Tool.tsx"
echo "- UrlEncoder.tsx"
echo "- JsonFormatter.tsx"
echo "- HtmlToText.tsx"
echo "- CsvToJson.tsx"
echo ""
echo "生成器:"
echo "- UuidGenerator.tsx"
echo "- QrGenerator.tsx"
echo "- LoremIpsum.tsx"
echo "- RandomPicker.tsx"
echo ""
echo "计算器:"
echo "- BmiCalculator.tsx"
echo "- AgeCalculator.tsx"
echo "- DateCalculator.tsx"
echo "- PercentageCalculator.tsx"
echo "- InterestCalculator.tsx"
echo "- InvestmentCalculator.tsx"
echo "- LoanCalculator.tsx"
echo "- CreditCardCalculator.tsx"
echo ""
echo "开发工具:"
echo "- HashGenerator.tsx"
echo "- RegexTester.tsx"
echo "- MarkdownPreview.tsx"
echo "- TimestampConverter.tsx"
echo ""
echo "图像/其他:"
echo "- ColorPicker.tsx"
echo "- ImageResizer.tsx"
echo "- ImageCompressor.tsx"
echo "- CurrencyConverter.tsx"
echo "- UnitConverter.tsx"
echo ""
echo "=========================="
